version: "3"

networks:
  database:
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: .
      target: runner
    ports:
      - 8000:8000
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/app
      - .env.development:/usr/src/app/.env
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - database

  db:
    container_name: db
    image: postgres:15
    tty: true
    ports:
      - 5432:5432
    volumes:
      - .data_dev:/var/lib/postgresql/data
      - ./sql/migrations:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=inventory_dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    networks:
      - database

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 3307:8080
    environment:
      - ADMINER_DESIGN=dracula
    networks:
      - database
